# Generated by Django 2.1.5 on 2019-01-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytodo', '0005_auto_20190113_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tudesday'), ('WEDENSDAY', 'Wedensday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10, verbose_name='Day of this schedule'),
        ),
    ]
