# Generated by Django 2.1.3 on 2019-01-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytodo', '0006_auto_20190113_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10, verbose_name='Day of this schedule'),
        ),
    ]
